package solutions;

/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 */

public class Solution389 {
    public char findTheDifference(String s, String t) {
        int bits = 1;
        for (char c: s.toCharArray())
            bits ^= (int)c;
        for (char c: t.toCharArray())
            bits ^= (int)c;
        return (char)(bits ^ 1);
    }
}